on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # You can specify a different Node.js version if needed

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run  # Replace with your actual Cypress test command
