  name: Node.js CI

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use your desired Node.js version
  
      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/Cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
  
      - name: Install dependencies
        run: npm install
  
      - name: Install Cypress
        run: npx cypress install
  
      - name: Run Cypress tests
        run: npx cypress open
